name: Deployment Pipeline

on:
  push:
    branches:
      - main

jobs: 
  deploy:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testdb
    steps:
      - uses: actions/checkout@v4
      - name : Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/testdb
          SPRING_DATASOURCE_USERNAME: root
          SPRING_DATASOURCE_PASSWORD: root
        run: mvn clean verify
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1.6
        env:
          projectKey: group-e-desapp_2024s2-desapp-grupo-e
          organization: group-e-desapp
          token: bf4035fe80911577282dda1c66e3143edeb1ebe3